name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file QQBot/pom.xml -X  # 生成详细日志

    - name: List current directory
      run: ls -al

    - name: List target directory
      run: ls -al target/ || echo "target directory does not exist"

    - name: Check Maven build result
      run: |
        if [ -d "target" ]; then
          echo "Build succeeded, target directory exists."
        else
          echo "Build failed or target directory does not exist."
          exit 1
        fi

    - name: Set up Git user
      run: |
        git config --global user.email "2061625072@qq.com"
        git config --global user.name "xinge4088"

    - name: Create a new tag
      run: |
        git tag -a v1.0.${{ github.run_number }} -m "Release version v1.0.${{ github.run_number }}"
        git push origin v1.0.${{ github.run_number }}

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload JAR to Release
      if: success() && steps.create_release.outputs.upload_url
      run: |
        echo "Release creation succeeded"
        echo "You can download the JAR file from the following URL:"
        echo "https://github.com/${{ github.repository }}/releases/download/v1.0.${{ github.run_number }}/$(basename target/*.jar)"
